// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ping.sql

package database

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
